name: Build and Deploy to Gatsby
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build_and_deploy:
    name: Build & Deploy
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository code
      - uses: actions/checkout@v4
      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v4
        with:
          node-version: "20.13.x"
      - name: Restore static-assets
        id: cache-static-assets-restore
        uses: actions/cache/restore@v4
        with:
          path: public/static-assets
          key: ${{ runner.os }}-static-assets

      - run: yarn add sharp --ignore-engines
      - run: yarn
      - run: yarn build

      - name: Save static-assets
        id: cache-static-assets-save
        uses: actions/cache/save@v4
        with:
          path: public/static-assets
          key: ${{ steps.cache-static-assets-restore.outputs.cache-primary-key }}

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -r --delete-after --quiet -e "ssh -o StrictHostKeyChecking=no"
          path: out/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
