name: Build and Deploy to Gatsby
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build_and_deploy:
    name: Build & Deploy
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository code
      - uses: actions/checkout@v4
      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v4
        with:
          node-version: "20.13.x"

      - name: Install Dependencies
        run: |
          yarn add sharp --ignore-engines
          yarn

      - name: Process Images
        run: yarn download:assets

      - name: Build Pages
        run: yarn build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -r --delete-after --quiet -e "ssh -o StrictHostKeyChecking=no"
          path: out/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
