name: Build and Deploy to Gatsby
on:
  schedule:
    # run daily at midnight to get random home page hehe
    - cron: '0 0 * * *'
  push:
    branches:
    - master
jobs:
  build_and_deploy:
    name: Build & Deploy
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository code
      - uses: actions/checkout@v2
      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: yarn
      # This triggers `gatsby build` script in "package.json"
      - run: yarn build --write-to-file --log-pages

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -r --delete-after --quiet -e "ssh -o StrictHostKeyChecking=no"
          path: public/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
